version: '2'
services:
  server:
    build:
      context: ./
    command: /usr/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./
    command: npm run start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
